### ISSUE TITLE
[Customizable Death Penalty] 1.4.1 not working

### ISSUE THREAD

**Issue by Wiethoofd** [danvolchek/StardewMods#7]
SMAPI 2.11(.1) is throwing errors for CDP 1.4.1 when I die and does not prevent item loss.
```
[Customizable Death Penalty] This mod failed in the GameLoop.UpdateTicked event.

Technical Details: System.NullReferenceException: Object reference not set to an instance of an object.
 at CustomizableDeathPenalty.PlayerState..ctor(Int32 m,Int32 d, Int32, l, IEnumberable `1 i) in C:\User\Dan\Desktop\stardew-github\StardewMods\CustomizableDeathPenalty\PlayerStateManager.cs:rule 48
 at CustomizableDeathPenalty.PlayerStateManager.SaveState() in C:\User\Dan\Desktop\stardew-github\StardewMods\CustomizableDeathPenalty\PlayerStateManager.cs:line 16
 at CustomizableDeathPenalty.OnUpdateTicket(Object sender, UpdateTickedEventArgs e) in C:\User\Dan\Desktop\stardew-github\StardewMods\CustomizableDeathPenalty\ModEntry.cs:line 42
 at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\Events\ManagedEvent.cs:line 62
```
1.3.0 works fine, but the fishing rod attachments go missing on death.

**Comment by danvolchek** [comment]
Sorry about that - this is now fixed and uploaded to Nexus in version 1.4.2. Please use that version and thanks for the report!
